coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: "pass"
    project:
      default:
        target: auto
      frontend:
        target: 100%
        flags:
          - frontend
    patch:
      default:
        target: 100%
      frontend:
        flags:
          - frontend
