codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false

coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: "pass"
    project:
      default:
        flags:
          - all
    patch:
      default:
        flags:
          - all
