codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    default_rules:
      flag_coverage_not_uploaded_behavior: "pass"
    project:
      default:
        flags:
          - all
    patch:
      default:
        flags:
          - all
