version: 2.1
setup: true

orbs:
  path-filtering: circleci/path-filtering@0.1.1

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          mapping: |
            api/.* test-api-job true
            web/.* test-frontend-job true
